var enviroment_ens;
var enviroment_launch;
if (location.hostname === "www.banamex.com" || location.hostname === "portal.banamex.com.mx") {
  enviroment_ens = "prod";
  // enviroment_launch = "launch-349d0818302c.min.js"
} else {
  enviroment_ens = "stage";
  // enviroment_launch = "launch-8150aa0e7708-staging.min.js";    
}

var ayudaurgente = [
   '/ayuda-urgente/cargos-no-reconocidos.html',
   '/ayuda-urgente/como-puedo-dar-seguimiento-a-mi-aclaracion.html',
   '/ayuda-urgente/index.html',
   '/ayuda-urgente/me-robaron-mi-tarjeta-de-credito.html',
   '/ayuda-urgente/mi-compra-no-aparece-a-meses-sin-intereses.html',
   '/ayuda-urgente/necesito-bloquear-mi-tarjeta.html',
   '/ayuda-urgente/necesito-cambiar-mi-contrasena.html',
   '/ayuda-urgente/no-veo-reflejado-un-deposito-o-transferencia.html',
   '/ayuda-urgente/olvide-mi-contrasena.html',
   '/ayuda-urgente/quiero-reportar-un-siniestro.html',
   '/ayuda-urgente/tengo-un-problema-con-mi-netkey.html'
];

var bancapatrimonial = [
    '/bancapatrimonial/beneficios-exclusivos-citibanamex.html',
    '/bancapatrimonial/contactanos/index.html',
    '/bancapatrimonial/fondos-esg.html',
    '/bancapatrimonial/inicio.html',
    '/bancapatrimonial/mercado-de-dinero.html',
    '/bancapatrimonial/plan-patrimonial-citibanamex.html',
    '/bancapatrimonial/portafolios-estrategicos-gold.html'
];

var compromiso = [
    '/compromiso-social/arte-y-cultura/index.html',
    '/compromiso-social/desarrollo-social/index.html',
    '/compromiso-social/directorio.html',
    '/compromiso-social/educacion/index.html',
    '/compromiso-social/medio-ambiente-y-sustentabilidad/index.html',
    '/compromiso-social/nota/index.html',
    '/compromiso-social/nota/1159.html',
    '/compromiso-social/nota/1336.html',
    '/compromiso-social/nota/139.html',
    '/compromiso-social/nota/1436.html',
    '/compromiso-social/nota/1716.html',
    '/compromiso-social/nota/1736.html',
    '/compromiso-social/nota/178.html',
    '/compromiso-social/nota/181.html',
    '/compromiso-social/nota/254.html',
    '/compromiso-social/nota/434.html',
    '/compromiso-social/nota/787.html',
    '/compromiso-social/nota/874.html',
    '/compromiso-social/programa/index.html',
    '/compromiso-social/proyecto/index.html',
    '/compromiso-social/quienes-somos.html'
];

var centrodeayuda = [
   '/es/centro-de-ayuda/afore/ahorro/aportaciones-complementarias-de-retiro-acr.htm',
   '/es/centro-de-ayuda/afore/ahorro/aportaciones-de-ahorro-largo-plazo.htm',
   '/es/centro-de-ayuda/afore/ahorro/aportaciones-voluntarias-afore-citibanamex.htm',
   '/es/centro-de-ayuda/afore/ahorro/aportaciones-voluntarias-inversion-largo-plazo-afore.htm',
   '/es/centro-de-ayuda/afore/ahorro/aportaciones-voluntarias-siefores-basicas.htm',
   '/es/centro-de-ayuda/afore/ahorro/consejos-para-el-ahorro.htm',
   '/es/centro-de-ayuda/afore/ahorro/index.html',
   '/es/centro-de-ayuda/afore/ahorro/retiro-de-aportaciones-voluntarias.htm',
   '/es/centro-de-ayuda/afore/servicios/carta-de-derechos.htm',
   '/es/centro-de-ayuda/afore/servicios/designacion-de-beneficiarios.htm',
   '/es/centro-de-ayuda/afore/servicios/estado-de-cuenta-y-saldo.htm',
   '/es/centro-de-ayuda/afore/servicios/expendiente-de-identificacion-afore.htm',
   '/es/centro-de-ayuda/afore/servicios/index.html',
   '/es/centro-de-ayuda/afore/servicios/registro-y-traspaso-de-afore.htm',
   '/es/centro-de-ayuda/afore/servicios/separacion-de-cuentas.htm',
   '/es/centro-de-ayuda/afore/servicios/traspaso-sar.htm',
   '/es/centro-de-ayuda/afore/tramites-de-retiro/cesantia-de-edad-avanzada.htm',
   '/es/centro-de-ayuda/afore/tramites-de-retiro/index.html',
   '/es/centro-de-ayuda/afore/tramites-de-retiro/proximo-a-pensionarte.htm',
   '/es/centro-de-ayuda/afore/tramites-de-retiro/retiro-imss.htm',
   '/es/centro-de-ayuda/afore/tramites-de-retiro/retiro-issste.htm',
   '/es/centro-de-ayuda/afore/tramites-de-retiro/retiro-por-desempleo-imss.htm',
   '/es/centro-de-ayuda/afore/tramites-de-retiro/retiro-por-desempleo-issste.htm',
   '/es/centro-de-ayuda/afore/tramites-de-retiro/retiros-parciales-afore.htm',
   '/es/centro-de-ayuda/creditos/hipotecarios/aclaraciones.htm',
   '/es/centro-de-ayuda/creditos/hipotecarios/apoyo-infonavit.htm',
   '/es/centro-de-ayuda/creditos/hipotecarios/documentos.htm',
   '/es/centro-de-ayuda/creditos/hipotecarios/index.html',
   '/es/centro-de-ayuda/creditos/hipotecarios/otros-temas.htm',
   '/es/centro-de-ayuda/creditos/hipotecarios/pago-y-domiciliacion.htm',
   '/es/centro-de-ayuda/creditos/hipotecarios/seguros.htm',
   '/es/centro-de-ayuda/cuentas/index.html',
   '/es/centro-de-ayuda/cuentas/actualiza-tus-datos/como-actualizar-mis-datos.htm',
   '/es/centro-de-ayuda/cuentas/actualiza-tus-datos/index.htm',
   '/es/centro-de-ayuda/cuentas/actualiza-tus-datos/por-que-actualizar-mis-datos.htm',
   '/es/centro-de-ayuda/cuentas/ahorro-facil/ahorro-automatico.htm',
   '/es/centro-de-ayuda/cuentas/ahorro-facil/cedes_citibanamex.html',
   '/es/centro-de-ayuda/cuentas/ahorro-facil/conocelo.htm',
   '/es/centro-de-ayuda/cuentas/ahorro-facil/index.htm',
   '/es/centro-de-ayuda/cuentas/ahorro-facil/pagare_citibanamex.html',
   '/es/centro-de-ayuda/cuentas/apertura-de-cuentas-en-linea/apertura.htm',
   '/es/centro-de-ayuda/cuentas/apertura-de-cuentas-en-linea/conocela.htm',
   '/es/centro-de-ayuda/cuentas/apertura-de-cuentas-en-linea/index.htm',
   '/es/centro-de-ayuda/cuentas/cuenta-priority.html',
   '/es/centro-de-ayuda/cuentas/index.htm',
   '/es/centro-de-ayuda/cuentas/mi-cuenta.html',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/ahorro.htm',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/banca-digital.htm',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/comisiones.htm',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/conocela.htm',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/index.htm',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/nomina-para-expatriados.htm',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/pagos-y-depositos.htm',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/portabilidad-de-nomina.htm',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/seguro-por-muerte-accidental.htm',
   '/es/centro-de-ayuda/cuentas/nomina-citibanamex/tarjetas-adicionales.htm',
   '/es/centro-de-ayuda/cuentas/protege-tu-identidad/index.htm',
   '/es/centro-de-ayuda/cuentas/protege-tu-identidad/personas-fisicas.htm',
   '/es/centro-de-ayuda/cuentas/protege-tu-identidad/personas-morales.htm',
   '/es/centro-de-ayuda/firma-electronica/3-pasos-de-la-firma-electronica.htm',
   '/es/centro-de-ayuda/firma-electronica/activa-tu-firma-electronica.htm',
   '/es/centro-de-ayuda/firma-electronica/firmar-es-seguro.htm',
   '/es/centro-de-ayuda/firma-electronica/index.html',
   '/es/centro-de-ayuda/firma-electronica/nomina-y-empresas.htm',
   '/es/centro-de-ayuda/firma-electronica/seguridad.htm',
   '/es/centro-de-ayuda/firma-electronica/solicita-tu-firma-electronica.htm',
   '/es/centro-de-ayuda/fondos-inversion/black-rock.htm',
   '/es/centro-de-ayuda/fondos-inversion/conoce-que-cambia-inversiones.htm',
   '/es/centro-de-ayuda/fondos-inversion/index.html',
   '/es/centro-de-ayuda/servicios-digitales/ahorro-facil/ahorro-facil.html',
   '/es/centro-de-ayuda/servicios-digitales/ahorro-facil/deposito-retiro-inversion.html',
   '/es/centro-de-ayuda/servicios-digitales/ahorro-facil/index.html',
   '/es/centro-de-ayuda/servicios-digitales/audiomatico/horarios.htm',
   '/es/centro-de-ayuda/servicios-digitales/audiomatico/index.html',
   '/es/centro-de-ayuda/servicios-digitales/audiomatico/ingreso.htm',
   '/es/centro-de-ayuda/servicios-digitales/audiomatico/ingreso-nip.htm',
   '/es/centro-de-ayuda/servicios-digitales/audiomatico/menu.htm',
   '/es/centro-de-ayuda/servicios-digitales/audiomatico/numero-secreto.htm',
   '/es/centro-de-ayuda/servicios-digitales/audiomatico/operatividad.htm',
   '/es/centro-de-ayuda/servicios-digitales/audiomatico/transacciones-bancarias.htm',
   '/es/centro-de-ayuda/servicios-digitales/banca-electronica/ingreso-banca-electronica.html',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/acceso.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/alta-baja-modificacion-de-cuentas.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/certificacion-de-celular.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/claves-de-acceso.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/configuracion.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/conocela.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/detalle-de-cuentas.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/domiciliacion.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/index.html',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/pago-de-tenencia-predial.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/saldos-y-movimientos.htm',
   '/es/centro-de-ayuda/servicios-digitales/bancanet/transferencias-pagos.htm',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/atmservicios.htm',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/cargos-comisiones.htm',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/cambio-de-nip.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/consulta-de-movimientos.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/consulta-de-saldos.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/deposito-de-cheques.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/deposito-de-efectivo.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/index.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/paga-tu-tarjeta-de-credito-con-cuenta-de-debito.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/pago-de-servicios-en-efectivo.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/pago-de-tarjeta-de-credito.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/retiro-de-efectivo.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/transfiere-a-cuenta-de-cheques-desde-cajeros-citibanamex.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/guias-de-uso-cajeros/transfiere-a-cuenta-de-debito-desde-cajeros-citibanamex.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/index.html',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/mantenimiento-atm.htm',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/operaciones.htm',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/operaciones-nuevos-cajeros.htm',
   '/es/centro-de-ayuda/servicios-digitales/cajeros/servicios-nuevos-cajeros.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-afore/aportaciones-voluntarias.html',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-afore/index.html',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-afore/orden-de-pago-desempleo.html',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-afore/retiro-por-desempleo.html',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-afore/ver-saldo-afore-citibanamex-en-bancanet.html',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/acceso-primera-vez.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/administracion-tarjetas-cuentas.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/ayuda.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/celular-verificado.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/cobro-digital.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/contrasenas.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/cotizador-seguros-citibanamex.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/cotizador-sucursales-y-cajeros.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/guias-netkey.html',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/guias-netkey-movil.html',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/haz-tus-operaciones.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/index.html',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/inicio.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/netkey.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/notificaciones-app.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/numero-de-cliente.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/pagos-y-transferencias.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/paypal.htm',
   '/es/centro-de-ayuda/servicios-digitales/citibanamex-movil/saldos-y-movimientos.htm',
   '/es/centro-de-ayuda/servicios-digitales/estado-de-cuenta/bancanet-conocelo.htm',
   '/es/centro-de-ayuda/servicios-digitales/estado-de-cuenta/bancanet-descargalo.htm',
   '/es/centro-de-ayuda/servicios-digitales/estado-de-cuenta/email-consultalo.htm',
   '/es/centro-de-ayuda/servicios-digitales/estado-de-cuenta/email-llave-de-acceso.htm',
   '/es/centro-de-ayuda/servicios-digitales/estado-de-cuenta/email-solicitalo.htm',
   '/es/centro-de-ayuda/servicios-digitales/estado-de-cuenta/index.html',
   '/es/centro-de-ayuda/servicios-digitales/geolocalizacion/conocelo.htm',
   '/es/centro-de-ayuda/servicios-digitales/geolocalizacion/index.html',
   '/es/centro-de-ayuda/servicios-digitales/localiza-tu-tarjeta/index.html',
   '/es/centro-de-ayuda/servicios-digitales/notificaciones/descripcion.htm',
   '/es/centro-de-ayuda/servicios-digitales/notificaciones/especificaciones.htm',
   '/es/centro-de-ayuda/servicios-digitales/notificaciones/index.html',
   '/es/centro-de-ayuda/servicios-digitales/notificaciones/mantente-informado.htm',
   '/es/centro-de-ayuda/servicios-digitales/portabilidad-nomina/cancelacion-de-tu-portabilidad.html',
   '/es/centro-de-ayuda/servicios-digitales/portabilidad-nomina/guias-portabilidad-nomina.html',
   '/es/centro-de-ayuda/servicios-digitales/portabilidad-nomina/index.html',
   '/es/centro-de-ayuda/servicios-digitales/portabilidad-nomina/portabilidad-citibanamex-movil.html',
   '/es/centro-de-ayuda/servicios-digitales/portabilidad-nomina/portabilidad-desde-bancanet.html',
   '/es/centro-de-ayuda/servicios-digitales/smart-statement/conocelo.htm',
   '/es/centro-de-ayuda/servicios-digitales/smart-statement/descargalo.htm',
   '/es/centro-de-ayuda/servicios-digitales/smart-statement/index.html',
   '/es/centro-de-ayuda/servicios-digitales/tarjetas/activar-promocion-6-meses-sin-intereses-bancanet.html',
   '/es/centro-de-ayuda/servicios-digitales/tarjetas/activar-promocion-6-meses-sin-intereses-cajeros.html',
   '/es/centro-de-ayuda/servicios-digitales/tarjetas/activar-promocion-6-meses-sin-intereses-citibanamex-movil.html',
   '/es/centro-de-ayuda/servicios-digitales/tarjetas/activar-tarjeta-de-credito-bancanet.html',
   '/es/centro-de-ayuda/servicios-digitales/tarjetas/activar-tarjeta-de-credito-citibanamex-movil.html',
   '/es/centro-de-ayuda/servicios-digitales/tarjetas/index.html',
   '/es/centro-de-ayuda/servicios-financieros/domiciliacion.htm',
   '/es/centro-de-ayuda/servicios-financieros/index.html',
   '/es/centro-de-ayuda/tarjetas/aclaraciones-de-tarjeta-de-credito.htm',
   '/es/centro-de-ayuda/tarjetas/activar-tarjeta-de-credito.htm',
   '/es/centro-de-ayuda/tarjetas/alertas-y-notificaciones.htm',
   '/es/centro-de-ayuda/tarjetas/cancelar-tarjetas-de-credito.htm',
   '/es/centro-de-ayuda/tarjetas/caracteristicas-de-las-tarjetas-de-credito.htm',
   '/es/centro-de-ayuda/tarjetas/clabe.htm',
   '/es/centro-de-ayuda/tarjetas/cvv-dinamico.htm',
   '/es/centro-de-ayuda/tarjetas/disponible-citibanamex.htm',
   '/es/centro-de-ayuda/tarjetas/estado-de-cuenta.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/beneficiarios.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/cancelacion-de-creditos-por-fallecimiento.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/cancelacion-de-productos-por-fallecimiento.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/cancelacion-tarjetas-de-credito-por-fallecimiento.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/cobro-por-fallecimiento.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/cuentas-debito-inversiones.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/deja-todo-en-orden.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/dudas-generales-tramite-por-fallecimiento.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/index.html',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/orientacion-tramites-por-fallecimiento.htm',
   '/es/centro-de-ayuda/tarjetas/guia-de-tramites-por-fallecimiento/tramites-seguros-por-fallecimiento.htm',
   '/es/centro-de-ayuda/tarjetas/incremento-de-linea.htm',
   '/es/centro-de-ayuda/tarjetas/operaciones-con-tarjeta-de-credito.htm',
   '/es/centro-de-ayuda/tarjetas/pagar-con-paypal.htm',
   '/es/centro-de-ayuda/tarjetas/puntos-premia.htm',
   '/es/centro-de-ayuda/tarjetas/requisitos-para-tarjetas-de-credito.htm',
   '/es/centro-de-ayuda/tarjetas/solicitud-para-tarjetas-de-credito.htm',
   '/es/centro-de-ayuda/tarjetas/tarjeta-de-credito-best-buy.htm',
   '/es/centro-de-ayuda/tarjetas/tarjetas-adicionales/activala.htm',
   '/es/centro-de-ayuda/tarjetas/tarjetas-adicionales/actualizacion-datos.htm',
   '/es/centro-de-ayuda/tarjetas/tarjetas-adicionales/beneficios.htm',
   '/es/centro-de-ayuda/tarjetas/tarjetas-adicionales/conoce-como-funcionan.htm',
   '/es/centro-de-ayuda/tarjetas/tarjetas-adicionales/costos-y-comisiones.htm',
   '/es/centro-de-ayuda/tarjetas/tarjetas-adicionales/manten-el-control.htm',
   '/es/centro-de-ayuda/tarjetas/tarjetas-adicionales/solicitalas.htm',
   '/es/centro-de-ayuda/tarjetas/tarjetas-adicionales/tarjetas-de-credito-adicionales.htm',
   '/es/centro-de-ayuda/tarjetas/transferencia-de-deuda.htm',
   '/es/centro-de-ayuda/tarjetas/usos-y-ventajas-de-las-tarjetas-de-credito.htm',

];

var conoce = [
    '/es/conoce_banamex/eventos/premio_micro_empresa.htm',
    '/es/conoce_banamex/eventos/teleton.htm',
    '/es/conoce_banamex/informacion_financiera/accion_banamex.htm',
    '/es/conoce_banamex/informacion_financiera/accion_banamex_financiera.htm',
    '/es/conoce_banamex/informacion_financiera/arrendadora_banamex.htm',
    '/es/conoce_banamex/informacion_financiera/arrendadora_banamex_corp.htm',
    '/es/conoce_banamex/informacion_financiera/banco_consolidado.htm',
    '/es/conoce_banamex/informacion_financiera/casa_bolsa.htm',
    '/es/conoce_banamex/informacion_financiera/conciliacion.htm',
    '/es/conoce_banamex/informacion_financiera/credito_familiar/credito_familiar.htm',
    '/es/conoce_banamex/informacion_financiera/grupo_financiero_banamex/conciliacion.htm',
    '/es/conoce_banamex/informacion_financiera/grupo_financiero_banamex/grupo_financiero_banamex.htm',
    '/es/conoce_banamex/informacion_financiera/informacion_financiera_consolidado.htm',
    '/es/conoce_banamex/informacion_financiera/informes_bmv.htm',
    '/es/conoce_banamex/informacion_financiera/servicios_financieros_soriana.htm',
    '/es/conoce_banamex/informacion_financiera/tarjetas_banamex/info_financiera.htm',
    '/es/conoce_banamex/informacion_financiera/tarjetas_banamex/tarjetas_banamex.htm',
    '/es/conoce_banamex/quienes_somos/fomento_social.htm',
];

var empresasygobierno = [
    '/es/empresasygobierno/atencion-empresas-internacionales.html',
    '/es/empresasygobierno/cash-management/administracion-liquidez/cheques-dolares.htm',
    '/es/empresasygobierno/cash-management/administracion-liquidez/cheques-moneda-nacional.htm',
    '/es/empresasygobierno/cash-management/administracion-liquidez/index.html',
    '/es/empresasygobierno/cash-management/adquirente/call-center.htm',
    '/es/empresasygobierno/cash-management/adquirente/cargo-automatico.htm',
    '/es/empresasygobierno/cash-management/adquirente/ecommerce.htm',
    '/es/empresasygobierno/cash-management/adquirente/iacepta-movil.htm',
    '/es/empresasygobierno/cash-management/adquirente/interredes.htm',
    '/es/empresasygobierno/cash-management/adquirente/orion.htm',
    '/es/empresasygobierno/cash-management/adquirente/terminal-punto-venta.htm',
    '/es/empresasygobierno/cash-management/banca-electronica/bancanet.htm',
    '/es/empresasygobierno/cash-management/banca-electronica/bancanet-empresarial-movil.htm',
    '/es/empresasygobierno/cash-management/banca-electronica/bancanet-movil.htm',
    '/es/empresasygobierno/cash-management/banca-electronica/bancanet-premium.htm',
    '/es/empresasygobierno/cash-management/banca-electronica/citi-direct.htm',
    '/es/empresasygobierno/cash-management/banca-electronica/citi-direct-mobile.htm',
    '/es/empresasygobierno/cash-management/banca-electronica/index.html',
    '/es/empresasygobierno/cash-management/cobranza/bancanet-directo.htm',
    '/es/empresasygobierno/cash-management/cobranza/cobranza-universal.htm',
    '/es/empresasygobierno/cash-management/cobranza/deposito-dotacion-electronico.htm',
    '/es/empresasygobierno/cash-management/cobranza/deposito-electronico.htm',
    '/es/empresasygobierno/cash-management/cobranza/depositos-linea-captura.htm',
    '/es/empresasygobierno/cash-management/cobranza/depositos-referencia.htm',
    '/es/empresasygobierno/cash-management/cobranza/efectivo-electronico.htm',
    '/es/empresasygobierno/cash-management/cobranza/index.htm',
    '/es/empresasygobierno/cash-management/multiproducto/index.htm',
    '/es/empresasygobierno/cash-management/pagos/domiciliacion.htm',
    '/es/empresasygobierno/cash-management/pagos/index.htm',
    '/es/empresasygobierno/cash-management/pagos/manager-checks.htm',
    '/es/empresasygobierno/cash-management/pagos/nomina.htm',
    '/es/empresasygobierno/cash-management/pagos/ordenes_pago_referenciadas.htm',
    '/es/empresasygobierno/cash-management/pagos/ordenes_pago_tradicionales.htm',
    '/es/empresasygobierno/cash-management/pagos/pago-impuesto-aduanales.htm',
    '/es/empresasygobierno/cash-management/pagos/pago-impuesto-federales.htm',
    '/es/empresasygobierno/cash-management/pagos/pago-impuesto-servicios.htm',
    '/es/empresasygobierno/cash-management/pagos/pemex-gas.htm',
    '/es/empresasygobierno/cash-management/pagos/pemex-refinacion.htm',
    '/es/empresasygobierno/cash-management/pagos/sua.htm',
    '/es/empresasygobierno/cash-management/pagos/transferencias-cuentas.htm',
    '/es/empresasygobierno/cash-management/pagos/transferencias-interbancarias.htm',
    '/es/empresasygobierno/coberturas-riesgos/cambios-fx.htm',
    '/es/empresasygobierno/coberturas-riesgos/index.html',
    '/es/empresasygobierno/coberturas-riesgos/mercado-derivados.htm',
    '/es/empresasygobierno/contactanos/index.htm',
    '/es/empresasygobierno/financiamiento/comercio-exterior/cartas-credito-internet.htm',
    '/es/empresasygobierno/financiamiento/comercio-exterior/financiamiento.htm',
    '/es/empresasygobierno/financiamiento/corto-plazo/cadenas-nafinsa.htm',
    '/es/empresasygobierno/financiamiento/corto-plazo/cartas-credito.htm',
    '/es/empresasygobierno/financiamiento/corto-plazo/credito-simple.htm',
    '/es/empresasygobierno/financiamiento/corto-plazo/credito-simple-dolares.htm',
    '/es/empresasygobierno/financiamiento/corto-plazo/financiamiento-electronico-proveedores.htm',
    '/es/empresasygobierno/financiamiento/corto-plazo/lineas-sobregiro.htm',
    '/es/empresasygobierno/financiamiento/corto-plazo/pagare_electronico_banamex.htm',
    '/es/empresasygobierno/financiamiento/corto-plazo/plan-piso.htm',
    '/es/empresasygobierno/financiamiento/corto-plazo/prestamo-quirografario.htm',
    '/es/empresasygobierno/financiamiento/largo-plazo/arrendamiento-finananciero-corporativo.htm',
    '/es/empresasygobierno/financiamiento/largo-plazo/credito-inmobiliario.htm',
    '/es/empresasygobierno/financiamiento/largo-plazo/credito-puente.htm',
    '/es/empresasygobierno/financiamiento/largo-plazo/credito-refaccionario.htm',
    '/es/empresasygobierno/financiamiento/largo-plazo/garantia-prendaria.htm',
    '/es/empresasygobierno/financiamiento/largo-plazo/habilitacion-avio.htm',
    '/es/empresasygobierno/financiamiento/largo-plazo/hipotecario-industrial.htm',
    '/es/empresasygobierno/financiamiento/largo-plazo/prestamo-hipotecario.htm',
    '/es/empresasygobierno/inversiones/fiduciario/index.htm',
];

var leydetrasparencia = [
    '/es/ley_de_transparencia/contrato_de_deposito.htm',
    '/es/ley_de_transparencia/folletos.htm',
    '/es/ley_de_transparencia/formatos_aclaracion.htm',
    '/es/ley_de_transparencia/instituciones-credito.htm',
    '/es/ley_de_transparencia/productos_garantizados_ipab.htm',
    '/es/ley_de_transparencia/tasas_pasivas.htm',
];

var personas = [
   '/es/personas/banca-digital/sucursales-digitales.html',
   '/es/personas/creditos/credito-de-nomina/simulador-credito-de-nomina.html',
   '/es/personas/creditos/credito-de-nomina/simulador-credito-de-nomina-preautorizado.html',
   '/es/personas/creditos/credito-hipotecario/hipoteca-perfiles.html',
   '/es/personas/creditos/credito-hipotecario/hipoteca-perfiles/comisiones.html',
   '/es/personas/creditos/credito-hipotecario/hipoteca-perfiles/requisitos.html',
   '/es/personas/creditos/redisposicion-de-credito-de-nomina.html',
   '/es/personas/creditos/tabla-amortizacion.html',
   '/es/personas/cuentas/cuenta-base.html',
   '/es/personas/cuentas/cuenta-de-cheques-en-dolares.html',
   '/es/personas/cuentas/cuenta-de-cheques-moneda-nacional.html',
   '/es/personas/cuentas/cuenta-maestra-profesionista.html',
   '/es/personas/cuentas/cuenta-nomina-empresas/servicios.html',
   '/es/personas/cuentas/cuenta-productiva-en-dolares.html',
   '/es/personas/priority/fondos-esg.html',
   '/es/personas/tarjetas-credito/activa-tarjeta.html',
   '/es/personas/tarjetas-credito/disposicion-efectivo.html',
   '/es/personas/tarjetas-credito/servicios-base.html',
   '/es/personas/tarjetas-credito/servicios-beyond.html',
   '/es/personas/tarjetas-credito/servicios-costco.html',
   '/es/personas/tarjetas-credito/servicios-platinum.html',
   '/es/personas/tarjetas-credito/servicios-premier.html',
   '/es/personas/tarjetas-credito/servicios-prestige.html',
   '/es/personas/tarjetas-credito/servicios-rewards.html',
   '/es/personas/tarjetas-credito/tarjeta-base.html',
   '/es/personas/tarjetas-credito/tarjeta-bestbuy.html',
   '/es/personas/tarjetas-credito/tarjeta-bsmart.html',
   '/es/personas/tarjetas-credito/tarjeta-bsmart/tarifas-comisiones.html',
   '/es/personas/tarjetas-credito/tarjeta-bsmartu.html',
   '/es/personas/tarjetas-credito/tarjeta-bsmartu/tarifas-comisiones.html',
   '/es/personas/tarjetas-credito/tarjeta-costco.html',
   '/es/personas/tarjetas-credito/tarjeta-laverde.html',
   '/es/personas/tarjetas-credito/tarjeta-marti-clasica.html',
   '/es/personas/tarjetas-credito/tarjeta-office-depot.html',
   '/es/personas/tarjetas-credito/tarjeta-simplicity/tarifas-comisiones.html',
   '/es/personas/tarjetas-credito/tarjeta-toluca.html',
];

var fondosdeinversion = [
    '/fondos-de-inversion/index.html',
    '/fondos-de-inversion/fondo-de-inversion.html',
    '/fondos-de-inversion/porque-invertir-en-fondos-de-inversion.html',
];

var misfinanzas = [
    '/mis-finanzas/tarjetas-de-credito/affinity-card/tips-para-comprar-con-tu-affinity-card-en-zara-y-bershka.html',
    '/mis-finanzas/tarjetas-de-credito/comprar-boletos-de-conciertos-en-preventa-citibanamex.html',
    '/mis-finanzas/tarjetas-de-credito/que-es-la-fecha-de-corte-en-la-tarjeta-de-credito.html',
    '/mis-finanzas/tarjetas-de-credito/tips-para-viajar-en-carretera.html',
];

var pymes = [
   '/pymes/administracion/bancanet-empresarial.html',
   '/pymes/administracion/nomina.html',
   '/pymes/administracion/tarjeta-ejecutiva-citibanamex.html',
   '/pymes/cobranza/calculadora-de-beneficios.html',
   '/pymes/cobranza/cuenta-concentradora.html',
   '/pymes/cobranza/e-comm.html',
   '/pymes/cobranza/iacepta.html',
   '/pymes/cobranza/tasa-cero.html',
   '/pymes/cobranza/terminal-punto-de-venta.html',
   '/pymes/crecimiento/cedes.html',
   '/pymes/crecimiento/empresarial.html',
   '/pymes/crecimiento/fondos.html',
   '/pymes/crecimiento/pagare.html',
   '/pymes/financiamiento/negocios-sustentables.html',
   '/pymes/index.html',
   '/pymes/mujeremprendedora/index.html',
   '/pymes/paquete_pyme.html',
   '/pymes/programa-pymes-evolution.html',
   '/pymes/requisitos.html',
   '/pymes/seguridad/auto-empresarial.html',
   '/pymes/seguridad/negocio-protegido.html',
   '/pymes/simulador-credito-pyme/tabla-amortizacion.html',
];

var seguros = [
    '/seguros/formulario.html',
    '/seguros/plan-patrimonial.html',
    '/seguros/seguro-antirrobo-bolso-protegido-cbnx.html',
    '/seguros/seguro-de-casa-rentada.html',
    '/seguros/seguro-de-compras-protegidas.html',
    '/seguros/seguro-de-flotilla-protegida.html',
    '/seguros/seguro-de-local-comercial.html',
    '/seguros/seguro-de-local-comercial-rentado.html',
    '/seguros/seguro-de-viaje-casual.html',
    '/seguros/seguro-de-viajero.html',
];

var sitios = [
    '/sitios/analisis-financiero/registro.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/5-ciudades-mas-tecnologicas-del-mundo.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/7-apps-para-los-amantes-de-las-mascotas.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/alice-cooper-el-musico-que-marco-la-historia-del-rock.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/beneficios-de-tener-una-cuenta-de-debito.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/como-aprovechar-tu-tarjeta-de-credito-para-conciertos.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/como-pagar-tu-tarjeta-de-credito-desde-la-app.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/como-saber-si-un-sitio-es-seguro-para-comprar.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/con-los-expertos-el-desarrollo-de-la-tecnologia-financiera.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/conoce-a-arly-velasquez-nuevo-integrante-de-team-citi.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/conoce-la-terraza-gastronomica-y-deleita-tu-paladar.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/cual-es-tu-estilo-festivalero-descubrelo-aqui.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/dld-la-historia-detras-de-la-popular-banda-mexicana.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/el-origen-de-los-instrumentos-musicales-mas-famosos.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/festivales-que-no-te-puedes-perder-en-la-segunda-mitad-del-ano.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/la-musica-ideal-para-hacer-yoga-correr-e-ir-al-gym.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/la-musica-realmente-ayuda-a-dormir-bien.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/la-verdadera-historia-de-la-guitarra-electrica.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/metaverso-el-futuro-esta-aqui-y-te-contamos-que-es.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/mete-un-home-run-y-diviertete-en-el-beis.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/navidalia-el-parque-tematico-con-magia-navidena.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/nft-que-son-y-como-se-comen.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/por-que-el-box-es-el-deporte-mas-completo.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/que-es-el-deporte-adaptado.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/que-es-la-musica-8d-y-por-que-esta-de-moda.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/que-es-la-tecnologia-5g.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/que-son-las-fintechs-y-por-que-todos-hablan-de-ellas.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/sacale-jugo-a-tu-ano-con-estos-eventos.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/te-ensenamos-como-pagar-tus-servicios-desde-la-app-bancaria.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/transformacion-del-sector-bancario-tras-la-pandemia.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/tunka-el-reino-de-las-aves-una-peli-para-disfrutar-en-familia.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/vive-como-rockstar-como-tener-tu-primer-millon.html',
    '/sitios/capital-y-estilo-citibanamex/entretenimiento/vive-la-experiencia-inmersiva-de-frida-kahlo.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/10-playas-mas-hermosas-del-mundo.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/5-destinos-turisticos-pet-friendly-para-pasarla-de-lujo.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/checa-esta-ruta-de-pueblos-magicos-cerca-de-cdmx.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/como-hacer-el-pan-de-platano-perfecto.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/consejos-para-viajar-con-bebes-en-avion.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/cuanto-dinero-necesito-para-viajar-a-suiza.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/las-3-mejores-playitas-de-mexico-que-debes-conocer.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/las-ventajas-y-desventajas-de-viajar-con-ninos.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/los-mejores-lugares-para-tirarse-de-paracaidas-en-mexico.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/receta-sopa-de-lima-los-sabores-del-sureste.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/tips-para-viajar-a-estados-unidos-por-primera-vez.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/tu-mas-un-destino-cool-mas-un-seguro-de-viajeno-se-piensalo.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/ventajas-de-viajar-solo-antes-de-los-20.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/viaje-en-carretera-que-considerar-al-contratar-un-seguro-de-auto.html',
    '/sitios/capital-y-estilo-citibanamex/viajes/vive-experiencias-inigualables-y-cuida-tu-bolsillo.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/5-acciones-cotidianas-que-te-ayudaran-a-ahorrar-agua.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/5-acciones-en-casa-que-ayudan-al-planeta-y-a-tu-bolsillo.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/5-ideas-para-reusar-los-envases.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/5-tips-para-cuidar-tu-piel-despues-de-los-30.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/arma-un-presupuesto-para-decorar-tu-terraza.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/caracteristicas-de-las-mujeres-exitosas-en-los-negocios.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/claves-para-el-cuidado-de-la-salud-de-los-ninos.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/como-elegir-tu-primera-casa.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/como-funciona-la-energia-eolica.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/como-hacer-composta-en-casa.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/como-hacer-que-tu-perfume-dure-todo-el-dia.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/como-mantener-una-relacion-a-distancia.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/como-prepararme-para-irme-a-vivir-a-otro-pais.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/como-remodelar-tu-casa-y-administrar-tu-dinero.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/como-tener-una-buena-relacion-con-tu-dinero.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/con-los-expertos-5-pasos-para-salir-de-las-deudas.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/con-los-expertos-arma-tu-plan-de-ahorro-para-el-retiro.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/con-los-expertos-la-importancia-de-la-bancarizacion.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/con-los-expertos-que-es-el-open-banking.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/con-los-expertos-responsabilidad-social-en-las-empresas.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/conoce-tu-tipo-de-piel-y-los-productos-ideales-para-ti.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/consejos-para-combatir-el-insomnio.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/cual-es-la-importancia-de-seguir-capacitandote.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/estrenar-muebles-para-mi-depa-jamas-fue-tan-sencillo.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/home-office-facts-para-checar-tu-salud-mental.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/impacto-ambiental-positivo-en-las-empresas.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/inclusion-laboral-como-potenciar-el-talento-femenino.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/la-importancia-de-areas-verdes-en-las-ciudades.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/marketing-digital-el-empujon-para-que-tu-pyme-despegue.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/paperless-cuidar-al-planeta-esta-en-tus-manos.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/power-femenino-tips-para-mejorar-sus-finanzas.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/que-es-el-sindrome-de-la-abeja-reina.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/que-es-micromanaging-y-cuales-son-sus-prejuicios.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/que-plantas-tener-en-casa-para-cuidar-al-ambiente.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/que-queeee-planea-tus-regalos-de-fin-de-ano-de-una-vez.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/reciclar-ropa-ayuda-al-medio-ambiente-claro-que-si.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/se-un-buen-lider-y-promueve-el-ahorro-en-tus-colaboradores.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/si-te-preguntas-si-rentar-o-comprar-esto-es-para-ti.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/soy-freelancer-aplica-afore-para-mi.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/tips-para-aliviar-el-estres-y-la-ansiedad.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/tips-para-crear-un-cv-efectivo.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/tips-para-darle-una-nueva-vida-a-tu-closet.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/tips-para-impulsar-tu-negocio-consejos-para-emprendedores.html',
    '/sitios/capital-y-estilo-citibanamex/vida-trabajo/turismo-sustentable-ayuda-a-tu-entorno-cuando-viajes.html',
    '/sitios/comunicados-prensa/galeria.html',
];

var transfer = [
    '/transfer/centro-de-ayuda/app-transfer/depositos-y-retiros.htm',
    '/transfer/centro-de-ayuda/app-transfer/descarga-y-apertura-de-cuenta.htm',
    '/transfer/centro-de-ayuda/app-transfer/envios-de-dinero.htm',
    '/transfer/centro-de-ayuda/app-transfer/index.html',
    '/transfer/centro-de-ayuda/app-transfer/pago-con-codigo-qr.htm',
    '/transfer/centro-de-ayuda/app-transfer/pago-de-servicios.htm',
    '/transfer/centro-de-ayuda/app-transfer/saldo-y-movimientos.htm',
    '/transfer/centro-de-ayuda/app-transfer/seguridad-y-nip-transfer.htm',
    '/transfer/centro-de-ayuda/cuenta-transfer-citibanamex/index.html',
    '/transfer/centro-de-ayuda/cuenta-transfer-citibanamex/montos-y-comisiones.htm',
    '/transfer/centro-de-ayuda/tarjeta-saldazo/apertura-y-reposicion-de-tarjeta.htm',
    '/transfer/centro-de-ayuda/tarjeta-saldazo/consulta-de-saldo.htm',
    '/transfer/centro-de-ayuda/tarjeta-saldazo/depositos-y-otras-operaciones.htm',
    '/transfer/centro-de-ayuda/tarjeta-saldazo/index.html',
    '/transfer/cuenta-transfer-digital.html',
    '/transfer/index.html',
];

var otros = [
    '/activate/index.html',
    '/actualizaradicionales/index.html',
    '/adquierebeneficios/index.html',
    '/afore/retiro-citibanamex-afore.html',
    '/amarratutasa/index.html',
    '/beneficios-internos-ptu/index.html',
    '/beneficios-oro/formulario-oro.html',
    '/canales-digitales/index.html',
    '/citibanamex-te-premia/index.html',
    '/codi/index.html',
    '/comoenelcine/index.html',
    '/developer-hub/registro.html',
    '/es/buro_de_entidades_financieras.htm',
    '/es/empresa-familiar/quienes.html',
    '/es/empresas_corporativos/servicios/treasury-trade-solutions/global-billing.htm',
    '/es/mapa-del-sitio.html',
    '/es/nuevomenubne/navegadores.htm',
    '/es/redes_sociales.htm',
    '/es/robo_de_identidad.htm',
    '/es/terminos_condiciones.htm',
    '/ganametas/index.html',
    '/libracinepolis/index.html',
    '/netkey/index.html',
    '/pagosdigitales/index.html',
    '/paquete/index.html',
    '/planes-de-inversion-grandes-pasos/index.html',
    '/premia/index.html',
    '/priority/beneficios/index.html',
    '/simulador-hipotecario/tabla-amortizacion/index.html',
    '/tarjetas-de-credito/tarjetas-para-viajes.html',
    '/tarjetas-de-credito/ten-el-mejor-viaje-de-tu-vida.html',
    '/valparaiso/index.html',
    '/valparaiso-info.html',
    '/viajerobanamex/index.html'
];

const enable_launch_axf = {
  global: true,
  packages: {
    p01: true,
    p02: true,
    p03: true,
    p04: true,
    p05: true,
    p06: true,
    p07: true,
    p08: true,
    p09: true,
    p10: true,
    p11: true,
    p12: true,
    p13: true,
  }
};
const arrUrls = [
  {
    name: "Package 01",
    enabled: enable_launch_axf.packages.p01,
    paths: [
      '/afore/actualizar-datos-expediente-afore.html',
      '/afore/deducir-impuestos-constancia-isr-acr-afore.html',
      '/afore/estado-de-cuenta-afore.html',
      '/afore/retiro-de-afore-por-desempleo-matrimonio.html',
      '/afore/separacion-de-cuentas-afore.html',
      '/diasunicos/perfilador.html',
      '/eventos/index.html',
      '/tu-lugar-citibanamex/registro/trivia.html',
      '/ganaunamensualidad/index.html',
      '/hazte-cliente/index.html',
      '/hotsale/index.html',
      '/es/conoce_banamex/informacion_financiera/grupo_financiero_banamex/info_financiera.htm',
      '/la-promo-mas/index.html',
      '/citibanamex/index.html',
      '/transfiere-tu-deuda/index.html'
    ]
  },
  {
    name: 'Package 02',
    enabled: enable_launch_axf.packages.p02,
    paths: [
      '/comunicados/venta-banamex.html',
      '/es/privacidad_portal.htm',
      '/es/personas/creditos/credito-hipotecario.html',
      '/es/personas/creditos/credito-cambia-hipoteca.html',
      '/es/personas/creditos/cambia-tu-hipoteca-liquidez.html',
      '/es/personas/creditos/credito-hipotecario-liquidez.html',
      '/es/personas/creditos/credito-hipotecario-tasa-creciente.html',
      '/es/personas/creditos/credito-hipotecario-tasa-fija.html',
      '/es/instituto_banamex.htm',
      '/jovenes/index.html',
      '/es/empresasygobierno/servicios/treasury-trade-solutions/spring.html'
    ]
  },
  {
    name: 'Package 03',
    enabled: enable_launch_axf.packages.p03,
    paths: [
      '/landings/tarjetas-de-credito/index.html',
      '/es/personas/tarjetas-credito/tarjeta-affinity.html',
      '/es/personas/tarjetas-credito/tarjeta-beyond.html',
      '/es/personas/tarjetas-credito/tarjeta-clasica.html',
      '/es/empresasygobierno/financiamiento/tarjetas-de-credito-corporativas.html',
      '/es/personas/tarjetas-credito/tarjeta-homedepot.html',
      '/es/personas/tarjetas-credito/tarjeta-oro.html',
      '/es/personas/tarjetas-credito/tarjeta-platinum.html',
      '/es/personas/tarjetas-credito/tarjeta-premier.html',
      '/es/personas/tarjetas-credito/tarjeta-prestige.html',
      '/es/personas/tarjetas-credito/tarjeta-rewards.html',
      '/es/personas/tarjetas-credito/tarjeta-de-credito-sin-anualidad-simplicity.html',
      '/es/personas/tarjetas-credito/tarjeta-teleton.html',
      '/sitios/educacion-financiera/cursos-de-educacion-financiera/lecciones-de-educacion-financiera-privada.html',
      '/sitios/educacion-financiera/test-finanzas-personales-sanas/index.html',
    ]
  },
  {
    name: 'Package 04',
    enabled: enable_launch_axf.packages.p04,
    paths: [
      "/sitios/analisis-financiero/index.html",
      "/libra/index.html",
      "/es/empresasygobierno/cash-management/index.htm",
      "/pagosautomaticos/index.html",
      "/seguros/seguro-de-ahorro.html",
      "/seguros/seguro-de-retiro-de-efectivo.html",
      "/seguros/index.html"
    ]
  },
  {
    name: 'Package 05',
    enabled: enable_launch_axf.packages.p05,
    paths: [
      "/es/personas/priority/index.html",
      "/disponible/registro.html",
      "/sitios/educacion-financiera/index.html",
      "/es/personas/banca-digital/estado-de-cuenta.html",
      "/patrimonio/index.html",
      "/landings/tarjetas-de-debito/index.html",
      "/pymes/index.html"
    ]
  },
  {
    name: 'Package 06',
    enabled: enable_launch_axf.packages.p06,
    paths: [
      "/pymes/administracion/cuenta-de-cheques.html",
      "/es/cbm-banco/banco_consolidado.html",
      "/sitios/comunicados-prensa/index.html",
      "/es/empresasygobierno/financiamiento/eloans.html",
      "/cuenta-nomina-empresas/index.html",
      "/pymes/vender/index.html",
      "/pymes/solicitud-de-asesoria/index.html"
    ]
  },
  {
    name: 'Package 07',
    enabled: enable_launch_axf.packages.p07,
    paths: [
      "/telefonos-citibanamex.html",
      "/tutoriales/citibanamex-movil/index.html",
      "/120horas/interno/120/nuevo.html",
      "/es/personas/banca-digital/audiomatico.html",
      "/bajatutasa/index.html",
      "/sitios/capital-y-estilo-citibanamex/index.html",
      "/es/centro-de-ayuda/tarjetas/index.html",
      "/corresponsales/index.html",
      "/masparati/index.html",
      "/pase-anual-citibanamex/index.html",
      "/domiciliacion/index.html",
    ]
  },
  {
    name: 'Packages 08',
    enabled: enable_launch_axf.packages.p08,
    paths: [
      "/seguros/seguro-de-hospitalizacion-protegida.html",
      "/seguros/seguro-de-pyme-protegida.html"
    ]
  },
  {
    name: 'Package 09',
    enabled: enable_launch_axf.packages.p09,
    paths: [
        ...ayudaurgente,
        ...bancapatrimonial,
        ...compromiso,
        ...centrodeayuda,
        ...conoce,
        ...empresasygobierno,
        ...leydetrasparencia,
        ...personas,
        ...fondosdeinversion,
        ...misfinanzas,
        ...pymes,
        ...seguros,
        ...sitios,
        ...transfer,
        ...otros,
    ]
  },
  {
    name: "Package 10",
    enabled: enable_launch_axf.packages.p10,
    paths: [
      '/afore/expediente-de-identificacion-afore.html',
      '/developer-hub/index.html',
      '/experienciascitibanamex/index.html',
      '/pymes/administracion/compra-venta-de-divisas.html',
      '/solicita-tu-tarjeta-credito-en-linea/index.html',
      '/lineacreciente/index.html',
      '/tarjeta-credito-en-linea/index.html',
      '/estatus-credito-hipotecario/index.html',
      '/ganamas/index.html',
      '/seguros/seguro-de-pyme-protegida.html',
      '/ahorromillonario/index.html',
      '/sitios/blog/index.html',
      '/fondos-de-inversion/index.html',
      '/transfer/tarjeta-saldazo.html',
      '/premioeconomia/index.html',
      '/tasaspreferentes/index.html',
      '/solicita-tu-tarjeta-credito-en-linea/index.html',
      '/solicita-tu-tarjeta-credito-en-linea/b/index.html',
      '/solicita-tu-tarjeta-credito-en-linea/b/ty.html',
      '/solicita-tu-tarjeta-credito-en-linea/ty.html',
      '/solicita-tu-tarjeta-credito-en-linea/d/index.html',
      '/solicita-tu-tarjeta-credito-en-linea/d/ty.html',
    ],
  },
  {
    name: "Package 11",
    enabled: enable_launch_axf.packages.p11,
    paths: [
      '/afore/index.html',
      '/es/personas/banca-digital/app-afore-movil.html',
      '/afore/afiliacion-citibanamex-afore.html',
      '/diasunicos/index.html',
      '/ganaunamensualidad/registro.html',
      '/pymes/tuspagostehacenganar/index.html',
      '/es/personas/creditos/credito-de-nomina.html',
      '/es/personas/creditos/credito-hipotecario/simulador-credito-hipotecario.html',
      '/es/personas/creditos/solicitud-asesoria.html',
      '/es/personas/creditos/credito-personal.html',
      '/es/personas/cuentas/perfil-ejecutivo.html',
      '/forlife/index.html',
      '/index.html',
      '/seguros/seguro-de-accidentes.html',
      '/seguros/seguro-de-viaje.html',
      '/seguros/seguro-de-vida.html',
      '/abretucuentaygana/index.html',
      '/es/personas/banca-digital/citibanamex-movil.html',
      '/es/personas/banca-digital/funcionalidades-citibanamex-movil.html',
      '/buenfin/index.html',
      '/seguros/seguro-de-auto-protegido.html',
      '/seguros/seguro-de-casa-protegida.html',
      '/sitios/promociones/index.html',
      '/sitios/promociones/promocion/detalle.html',
      '/sitios/promociones/filtro.html'
    ],
  },
  {
    name: "Package 12",
    enabled: enable_launch_axf.packages.p12,
    paths: [
      '/es/empresasygobierno/cash-management/banca-electronica/index.html',
      '/es/personas/banca-digital/bancanet.html',
      '/contratar-tarjeta-en-linea-citibanamex/index.html',
      '/cvvdigital/index.html',
      '/disponible/index.html',
      '/es/personas/cuentas/mi-cuenta-debito.html',
      '/es/empresasygobierno/inversiones/fondos-de-inversion-citibanamex.htm',
      '/es/empresasygobierno/inversiones/inversion-empresarial.htm',
      '/es/empresasygobierno/inversiones/index.htm',
      '/es/empresasygobierno/inversiones/mercados-dinero.htm',
      '/es/empresasygobierno/inversiones/notas-estructuradas.htm',
      '/es/empresasygobierno/financiamiento/index.html',
      '/diversifica/index.html',
      '/es/personas/banca-digital/notificaciones.html',
      '/pymes/administracion/nuevo-paquete-pyme.html',
      '/pymes/administracion/pymes-alto-valor.html',
      '/pymes/financiamiento/credito-negocios.html',
      '/landings/tarjetas-de-credito/promocion-boleto-avion.html',
      '/portabilidad-de-nomina/index.html',
      '/regresatunomina/index.html',
      '/gana-un-auto/index.html'
    ],
  },
  {
    name: "Package 13",
    enabled: enable_launch_axf.packages.p13,
    paths: [
        '/120horas/index.html',
        '/afore/ahorro-voluntario.html',
        '/afore/traspaso-sar-imss.html',
        '/apple-pay/index.html',
        '/blkmega/index.html',
        '/bolsa-de-trabajo/index.html',
        '/buenfin/interno/registro/nuevo.html',
        '/centro-de-seguridad/index.html',
        '/cfdi/index.html',
        '/cobranza/index.html',
        '/compromiso-social/boletines-condusef.html',
        '/compromiso-social/filtro/index.html',
        '/compromiso-social/index.html',
        '/compromiso-social/informes-de-compromiso-social-ciudadania-corporativa.html',
        '/compromiso-social/informes-de-transparencia.html',
        '/contactanos/citapyme/index.html',
        '/contratar-cuenta-de-debito-en-linea/quiero-ser-cliente/codigo-qr.html',
        '/contratar-cuenta-de-debito-en-linea/quiero-ser-cliente/error.html',
        '/disponible/tabla-amortizacion.html',
        '/economia-finanzas/es/mercado-de-divisas/index.html',
        '/es/candidatos_colaboradores.htm',
        '/es/centro-de-ayuda/afore/index.html',
        '/es/empresasygobierno/index.html',
        '/es/experiencia/target.html',
        '/es/ley_de_transparencia/comisiones.htm',
        '/es/ley_de_transparencia/comisiones/avisos.htm',
        '/es/ley_de_transparencia/comisiones/cashmanagement_banca.htm',
        '/es/ley_de_transparencia/comisiones/productos_captacion.htm',
        '/es/localizador-sucursales.html',
        '/es/personas/banca-digital/cajeros-automaticos.html',
        '/es/personas/cuentas/cuenta-basica.html',
        '/es/personas/cuentas/cuenta-maestra.html',
        '/es/personas/cuentas/cuenta-perfiles.html',
        '/es/personas/cuentas/cuentapriority.html',
        '/es/personas/cuentas/mi-cuenta.html',
        '/es/personas/cuentas/perfilador-debito.html',
        '/es/personas/inversiones.html',
        '/es/personas/priority/productos.html',
        '/es/personas/servicios/aclaraciones-cargos-tarjetas/index.html',
        '/es/personas/servicios/banca-digital/wallet.html',
        '/es/personas/servicios_digitales/estado_cuenta_electronico.htm',
        '/es/personas/tarjetas-credito/beneficios-tarjetas-de-credito.html',
        '/es/personas/tarjetas-credito/pagos-fijos.html',
        '/es/personas/tarjetas-credito/programa-recompensas/thankyou-points.html',
        '/es/personas/tarjetas-credito/servicios.html',
        '/es/personas/tarjetas-credito/solicitar-tarjeta-de-credito.html',
        '/es/personas/tarjetas-credito/tabla-amortizacion.html',
        '/es/personas/tarjetas-credito/tarjeta-affinity/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-beyond/seguros.html',
        '/es/personas/tarjetas-credito/tarjeta-beyond/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-clasica/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-costco/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-homedepot/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-oro/seguros.html',
        '/es/personas/tarjetas-credito/tarjeta-oro/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-platinum/seguros.html',
        '/es/personas/tarjetas-credito/tarjeta-platinum/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-premier/seguros.html',
        '/es/personas/tarjetas-credito/tarjeta-premier/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-prestige/seguros.html',
        '/es/personas/tarjetas-credito/tarjeta-prestige/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-rewards/seguros.html',
        '/es/personas/tarjetas-credito/tarjeta-rewards/tarifas-comisiones.html',
        '/es/personas/tarjetas-credito/tarjeta-teleton/tarifas-comisiones.html',
        '/es/privacidad_transfer.htm',
        '/estamoscontigo/index.html',
        '/estamoscontigo/plan-personalizado.html',
        '/fondos-de-deuda/corto-plazo.html',
        '/hazmasdinero/index.html',
        '/impuestos/index.html',
        '/impuestosyservicios/index.html',
        '/loungekey/index.html',
        '/pase-anual-citibanamex/registro.html',
        '/reactivatucarrera/index.html',
        '/seguros/calculadora-seguro-accidentes/index.html',
        '/seguros/calculadora-seguro-vida/index.html',
        '/seguros/como-elegir-el-mejor-seguro.html',
        '/seguros/seguros-en-linea/',
        '/seguros/seguros-en-linea/index.html',
        '/sitios/aclaraciones-cargos-tarjetas/consulta-estatus.html',
        '/sitios/aclaraciones-cargos-tarjetas/index.html',
        '/sitios/analisis-financiero/buscador.html',
        '/sitios/comunicados-prensa/informacion.html',
        '/sitios/comunicados-prensa/venta-citibanamex/index.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/3-tasas-de-interes-para-dominar-tu-tarjeta-de-credito.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/5-cosas-muy-utiles-que-no-conocias-de-tu-app-bancaria.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/5-pasos-para-cobrar-tu-seguro-de-accidentes.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/aprende-a-leer-tu-estado-de-cuenta.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/aprender-a-administrar-y-dominar-tus-finanzas-personales.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/aprovecha-los-meses-sin-intereses.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/arriesgate-a-ganar.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/beneficiario-de-un-seguro-de-vida-descubre-si-lo-eres.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/boda-boda-ya-revisaste-tus-finanzas.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/cambia-tu-credito-hipotecario-y-paga-menos.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/codi-no-te-saques-de-onda-mejor-aprende-a-usarlo.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-administrar-tu-dinero-al-retirarte.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-apoyar-para-reactivar-la-economia-tras-la-pandemia.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-aprovechar-los-beneficios-de-mi-tarjeta-de-credito.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-elijo-la-mejor-tarjeta-de-credito.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-ensenar-el-espiritu-emprendedor-a-los-ninos.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-hacer-una-transferencia-bancaria.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-puedo-evaluar-mi-situacion-financiera.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-se-hace-un-presupuesto-y-para-que-sirve.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-usar-responsablemente-un-credito-de-liquidez.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/como-y-que-ensenarles-sobre-finanzas-a-tus-hijos-en-la-universidad.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/criptomonedas-y-otras-novedosas-formas-de-inversion.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/cuando-para-que-y-como-usar-un-prestamo-de-nomina.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/dale-la-vuelta-a-tu-historial-crediticio-con-estos-tips.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/datos-biometricos-la-mejor-forma-de-proteger-tu-dinero.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/descubre-como-generar-ingresos-extras.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/diferencias-y-similitudes-entre-cuenta-de-credito-y-debito.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/donde-debo-tener-mi-fondo-de-emergencia.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/donde-obtener-un-credito-hipotecario-y-como-elegirlo.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/efecto-bola-de-nieve.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/empieza-a-invertir.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/empieza-a-invertir-de-manera-sencilla-segura-y-eficiente.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/en-las-deudas-como-en-el-amor-hay-que-poner-limites.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/ensena-a-tus-hijos-sobre-dinero.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/ensenale-a-tus-hijos-como-funcionan-las-tarjetas-de-credito.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/guia-de-tarjeta-de-credito-para-novatos.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/guia-para-ahorrar-en-los-festivales-musicales.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/index.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/inversiones-sostenibles-de-que-tratan.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/inversion-sostenible-considera-estos-factores-antes.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/invertir-igual-a-beneficios-fiscales.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/invierte-en-bienes-raices-con-un-credito-hipotecario.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/lo-que-necesitas-saber-para-usar-tu-seguro-de-gastos-medicos-mayores.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/los-horoscopos-que-tu-historial-crediticio-dice-mas-de-ti.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/meses-sin-intereses-aprende-a-usarlos-sabiamente.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/por-que-contratar-un-seguro-de-vida.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/por-que-elegir-una-tarjeta-de-credito-sin-anualidad.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/por-que-incrementar-la-ciberseguridad-en-casa.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/puedo-elegir-donde-recibir-mi-cuenta-de-nomina.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/que-alguien-me-explique-que-ese-eso-del-ppr.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/que-estos-errores-no-te-sorprendan-al-pagar-tus-deuda.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/que-es-una-inversion-a-la-vista-y-para-que-sirve.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/que-es-una-tasa-preferencial-y-donde-la-consigo.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/que-pasa-con-las-afore.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/que-son-los-fondos-de-inversion-y-cuando-usarlos.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/que-tan-seguras-son-tus-contrasenas.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/recomendaciones-para-hacer-crecer-tus-ahorros.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/reduce-riesgos-con-tu-tarjeta-de-credito.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/reparto-de-utilidades.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/sabias-que-delincuentes-podrian-vender-tu-informacion.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/saca-el-maximo-provecho-a-tu-reparto-de-utilidades.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/sorprende-a-los-imprevistos-con-un-fondo-de-emergencia.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/tarjeta-de-debito-finanzas-mas-saludables.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/tener-seguro-de-vida-creenos-te-da-vida.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/tips-de-seguridad-para-herramientas-financieras-digitales.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/tips-para-bajarle-al-gasto-si-eres-comprador-compulsivo.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/tips-para-manejar-tus-finanzas-en-el-matrimonio.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/tips-para-planear-el-pago-de-la-universidad-de-tu-hijo.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/tips-para-tener-la-mejor-experiencia-al-comprar-en-linea.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/todo-lo-que-debes-saber-sobre-el-pago-de-impuestos.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/tramites-en-linea-que-ayudan-a-ahorrar-tiempo-y-dinero.html',
        '/sitios/educacion-financiera/blog-de-educacion-financiera/usos-y-abusos-de-tu-tarjeta-de-credito.html',
        '/sitios/promociones/filtro.html',
        '/tasas/index.html',
        '/tu-lugar-citibanamex/registro/pyme.html',
        '/bancapatrimonial/contactanos/index.html',
        '/bancapatrimonial/fondos-esg.html',
        '/es/personas/priority/perfilador.html',
        '/seguros/seguro-de-casa-propia.html',
        '/es/personas/cuentas/administracion/cuenta-perfiles/index.html',
        '/es/personas/cuentas/administracion/cuenta-perfiles/multi-form_page-v2.html',
        '/es/empresasygobierno/inversiones/fiduciario/productos.htm',
        '/es/empresasygobierno/inversiones/fiduciario/trust.htm',
        '/es/personas/cuentas/cuenta-nomina-empresas.html',
        '/es/personas/servicios/aclaraciones-cargos-tarjetas/cargos-form.html',
        '/es/tarjetas-premium/salones-beyond.html',
        '/mobile/es/canales-alternativos/index.htm',
        '/voluntariadobanamex/alianzas.htm',
        '/voluntariadobanamex/quienes_somos.htm',
        '/jovenes/index.html',
        '/seguros/seguro-de-salud-protegida.html'
    ],
  },
];

function usingLaunchAxf(arrUrls, path) {
  if (path.split('.').pop() != 'html' && path.split('.').pop() != 'htm')
    path = `${path}index.html`;
  return arrUrls.filter(
    item => item.enabled && item.paths.includes(path) || item.paths.includes('/Soporte_y_Desarrollo') 
  );
}

if (location.hostname != "boveda.banamex.com.mx") {
  var mbox = document.createElement('script');
  ensig = document.createElement('script');
  ensig.type = 'text/javascript';
  const pathName = location.pathname;
  if (enable_launch_axf.global && usingLaunchAxf(arrUrls, pathName).length > 0) {
    //ensig.src="assets.adobedtm.com/e8984c2d73c2/d7df1ac251f9/"+enviroment_launch;
  } else {
    //ensig.src = "//nexus.ensighten.com/citi/mex_" + enviroment_ens + "/Bootstrap.js";
  }
  document.head.appendChild(ensig);
  /*mbox.setAttribute('type', 'text/javascript');
  mbox.setAttribute('src', '/assets/js/mbox.js');
  document.getElementsByTagName('head')[0].appendChild(mbox);*/
}